export default {
  TOGGLE_SOUND_ON_COUNT: 'TOGGLE_SOUND_ON_COUNT',
  TOGGLE_SOUND_ON_CHANGE: 'TOGGLE_SOUND_ON_CHANGE',
  TOGGLE_VIBRATE_ON_COUNT: 'TOGGLE_VIBRATE_ON_COUNT',
  TOGGLE_VIBRATE_ON_CHANGE: 'TOGGLE_VIBRATE_ON_CHANGE',
}